services:
  hw10-postgres:
    image: postgres:latest
    container_name: hw10-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

  mongo:
    image: mongo:latest
    container_name: hw10-mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local